### ISSUE TITLE
Proposal: Make haliax.nn modules have an __init__ function which can be used to construct a skeleton tree

### ISSUE THREAD

**Issue by cooljoseph1** [stanford-crfm/haliax#104]
Right now the modules in haliax.nn have a static method init() which can be used to initialize a module *and create random weights for it*. I think we should also provide a function to construct just the skeleton of the module without creating any weights. This would be useful for loading pretrained weights into a model.

One way this could be implemented is by overriding \_\_init\_\_() to--if a weight/submodule is not provided--assign the weight to None/call \_\_init\_\_() on the submodule. Another way this could be implemented is by creating a MyModuleSkeleton class with these defaults and then subclassing it for the MyModule class.

**Comment by dlwh** [comment]
Hi @cooljoseph1 : Thanks for the suggestion.

Thanks to `jax.eval_shape` (and `eqx.filter_eval_shape`), you don't really need this. You can get the skeleton of a module by doing:

```python
skeleton = eqx.filter_eval_shape(MyModule.init, my_args, key=key)
```

Now you have the skeleton of the model with a bunch of ShapeDtypeStructs instead of actual arrays. I actually use this trick in Levanter a lot (and in named_jit)

**Comment by cooljoseph1** [comment]
I didn't realize equinox that function! Thanks for letting me know--that's definitely better.
